/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fravemaxsalesmanager.interfazDeUsuario;

import fravemaxsalesmanager.accesoADatos.ProductoData;
import fravemaxsalesmanager.entidades.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jfneg
 */
public class modificaInventario extends javax.swing.JInternalFrame {

    ProductoData proData = new ProductoData();
    
    public modificaInventario() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbuscarProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproductoSeleccionado = new javax.swing.JTable();
        jTbuscarID = new javax.swing.JTextField();

        jLbuscarProducto.setText("Buscar producto por ID: ");

        jTproductoSeleccionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Id Producto", ""},
                {"Categoría", ""},
                {"Nombre", null},
                {"Marca", null},
                {"Modelo", null},
                {"Descripción", null},
                {"Precio", null},
                {"Stock", null}
            },
            new String [] {
                "null", "Producto Seleccionado"
            }
        ));
        jScrollPane1.setViewportView(jTproductoSeleccionado);
        if (jTproductoSeleccionado.getColumnModel().getColumnCount() > 0) {
            jTproductoSeleccionado.getColumnModel().getColumn(1).setResizable(false);
        }

        jTbuscarID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTbuscarIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jTbuscarID)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTbuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbuscarIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscarIDKeyTyped

        try {      
       int id = Integer.parseInt( jTbuscarID.getText());
      
       
       Producto producto = proData.buscarProductoPorId(id);
       jTproductoSeleccionado.editCellAt(0,1);
       jTproductoSeleccionado.e
               
       
       
       
            
        } catch (NumberFormatException e ) {
            JOptionPane.showMessageDialog(null, "Ha ingresado una Id Inválida");
        }
    }//GEN-LAST:event_jTbuscarIDKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbuscarProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTbuscarID;
    private javax.swing.JTable jTproductoSeleccionado;
    // End of variables declaration//GEN-END:variables

 
}

