
package fravemaxsalesmanager.interfazDeUsuario;

import fravemaxsalesmanager.accesoADatos.ClienteData;
import fravemaxsalesmanager.accesoADatos.ProductoData;
import fravemaxsalesmanager.entidades.Cliente;
import fravemaxsalesmanager.entidades.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Belén
 */
public class ViewListarClienteProdX extends javax.swing.JInternalFrame {
     
    private ProductoData productoData;
    private ClienteData clienteData;

    
    public ViewListarClienteProdX() {
        initComponents();
        productoData = new ProductoData();
        clienteData = new ClienteData();
        llenarComboBoxProductos();
        llenarComboBoxClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jBGenerarInfoProd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProductosx = new javax.swing.JTable();
        jCBCliente = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Listar producto ");

        jLabel2.setText("Producto:");

        jCBProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente:");

        jBGenerarInfoProd.setText("Generar informe");
        jBGenerarInfoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarInfoProdActionPerformed(evt);
            }
        });

        jTProductosx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTProductosx);

        jCBCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBProducto, 0, 143, Short.MAX_VALUE)
                            .addComponent(jCBCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBGenerarInfoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBGenerarInfoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCBProductoActionPerformed

    private void jBGenerarInfoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarInfoProdActionPerformed
        // TODO add your handling code here:
        
        String productoSeleccionado = jCBProducto.getSelectedItem().toString();
        String clienteSeleccionado =jCBCliente.getSelectedItem().toString();
        
        Producto producto = (Producto) productoData.buscarProductoPorNombreProducto(productoSeleccionado);
        Cliente cliente = clienteData.obtenerClientesPorProducto(clienteSeleccionado);
        if (producto != null) {
            DefaultTableModel model = (DefaultTableModel) jTProductosx.getModel();
            model.setRowCount(0);
            List<Cliente> clientesQueCompraron = clienteData.obtenerClientesPorProducto(producto);
            for (Cliente cliente : clientesQueCompraron) {
                model.addRow(new Object[]{
                    cliente.getNombre(),
                    cliente.getApellido(),
                    cliente.getTelef(),
                    cliente.getEmail()
                });
            }
        } else {
            JOptionPane.showMessageDialog(this, "El producto seleccionado no existe.");
        }
    
        
    }//GEN-LAST:event_jBGenerarInfoProdActionPerformed

    private void jCBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGenerarInfoProd;
    private javax.swing.JComboBox<String> jCBCliente;
    private javax.swing.JComboBox<String> jCBProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProductosx;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

private void llenarComboBoxProductos() {
        jCBProducto.removeAllItems();
        List<Producto> productos = productoData.buscarProductoPorNombreProducto("");
        for (Producto producto : productos) {
            jCBProducto.addItem(producto.getNombreProducto());
        }
    }
 private void llenarComboBoxClientes() {
        jCBCliente.removeAllItems();
        List<Cliente> clientes = clienteData.obtenerTodosLosClientes(); // Reemplaza esto con el método adecuado para obtener los clientes
        for (Cliente cliente : clientes) {
            jCBCliente.addItem(cliente.getNombre()); // Puedes personalizar la forma en que se muestra el cliente en el JComboBox
        }
    }
}

