/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fravemaxsalesmanager.interfazDeUsuario;

import fravemaxsalesmanager.accesoADatos.ProductoData;
import fravemaxsalesmanager.entidades.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jfneg
 */
public class ViewModificaInventario extends javax.swing.JInternalFrame {

    ProductoData proData = new ProductoData();

    public ViewModificaInventario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbuscarProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproductoSeleccionado = new javax.swing.JTable();
        jTbuscarID = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();

        jLbuscarProducto.setText("Buscar producto por ID: ");

        jTproductoSeleccionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Id Producto", ""},
                {"Categoría", ""},
                {"Nombre", ""},
                {"Marca", null},
                {"Modelo", null},
                {"Descripción", null},
                {"Precio", null},
                {"Stock", null}
            },
            new String [] {
                "", "Producto Seleccionado"
            }
        ));
        jScrollPane1.setViewportView(jTproductoSeleccionado);
        if (jTproductoSeleccionado.getColumnModel().getColumnCount() > 0) {
            jTproductoSeleccionado.getColumnModel().getColumn(1).setResizable(false);
        }

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTbuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jBBuscar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTbuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        cargarDatosTabla();
    }//GEN-LAST:event_jBBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JLabel jLbuscarProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTbuscarID;
    private javax.swing.JTable jTproductoSeleccionado;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosTabla() {
        try {
            int id = Integer.parseInt(jTbuscarID.getText().replace(" ", ""));

            Producto producto = proData.buscarProductoPorId(id);
            if (producto.getIdProducto() == 0) { 
                jTproductoSeleccionado.setValueAt(null, 0, 1);
                jTproductoSeleccionado.setValueAt(null, 1, 1);
                jTproductoSeleccionado.setValueAt(null, 2, 1);
                jTproductoSeleccionado.setValueAt(null, 3, 1);
                jTproductoSeleccionado.setValueAt(null, 4, 1);
                jTproductoSeleccionado.setValueAt(null, 5, 1);
                jTproductoSeleccionado.setValueAt(null, 6, 1);
                jTproductoSeleccionado.setValueAt(null, 7, 1);
                JOptionPane.showMessageDialog(null, "Error, producto no encontrado.");
            } else {
                jTproductoSeleccionado.setValueAt(producto.getIdProducto(), 0, 1);
                jTproductoSeleccionado.setValueAt(producto.getCategoria(), 1, 1);
                jTproductoSeleccionado.setValueAt(producto.getNombreProducto(), 2, 1);
                jTproductoSeleccionado.setValueAt(producto.getMarca(), 3, 1);
                jTproductoSeleccionado.setValueAt(producto.getModelo(), 4, 1);
                jTproductoSeleccionado.setValueAt(producto.getDescripcion(), 5, 1);
                jTproductoSeleccionado.setValueAt(producto.getPrecioActual(), 6, 1);
                jTproductoSeleccionado.setValueAt(producto.getStock(), 7, 1);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ha ingresado una Id Inválida");
        }
    }
}
