/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fravemaxsalesmanager.interfazDeUsuario;

import fravemaxsalesmanager.accesoADatos.ProductoData;
import fravemaxsalesmanager.entidades.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author jfneg
 */
public class ViewAltaInventario extends javax.swing.JInternalFrame {

    private ProductoData proData = null;

    public ViewAltaInventario() {
        proData = new ProductoData();
        
          
        initComponents();
        cargarComboCategoria();
        cargarComboNombreProducto();
        cargarComboMarca();
        cargarComboModelo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fravemaxsalesmanager.interfazDeUsuario.Backinventarios();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCcategoria = new javax.swing.JComboBox<>();
        jCnombreProducto = new javax.swing.JComboBox<>();
        jCcomboMarca = new javax.swing.JComboBox<>();
        jCmodelo = new javax.swing.JComboBox<>();
        jTdescripcion = new javax.swing.JTextField();
        jTprecio = new javax.swing.JTextField();
        jTstock = new javax.swing.JTextField();
        jBaltaProducto = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jLabel1.setText("Categoría: ");

        jLabel2.setText("Nombre Producto:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Modelo:");

        jLabel5.setText("Descripción:");

        jLabel6.setText("Precio:");

        jLabel7.setText("Stock:");

        jCcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcategoriaActionPerformed(evt);
            }
        });

        jCnombreProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCnombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCnombreProductoActionPerformed(evt);
            }
        });

        jCcomboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCcomboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcomboMarcaActionPerformed(evt);
            }
        });

        jCmodelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmodeloActionPerformed(evt);
            }
        });

        jTdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdescripcionActionPerformed(evt);
            }
        });

        jBaltaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fravemaxsalesmanager/recursos/iconoGuardar.png"))); // NOI18N
        jBaltaProducto.setText("Grabar");
        jBaltaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaltaProductoActionPerformed(evt);
            }
        });

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fravemaxsalesmanager/recursos/cerrar.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Alta de Productos al Inventario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jBaltaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTstock, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCcomboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(248, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jCnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCcomboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jCmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTstock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaltaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdescripcionActionPerformed

    private void jBaltaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaltaProductoActionPerformed
        String categoria = (String)jCcategoria.getSelectedItem();
        String nombreProducto = (String)jCnombreProducto.getSelectedItem();
        String marca = (String)jCcomboMarca.getSelectedItem();
        String modelo = (String)jCmodelo.getSelectedItem();
        String descripcion =jTdescripcion.getText();
       
        //****************************************************************************//   
        
        try {
        Double precioActual = Double.parseDouble(jTprecio.getText());
        int stock = Integer.parseInt(jTstock.getText()); 
        Producto producto = new Producto(categoria, nombreProducto, marca, modelo, descripcion, precioActual, stock, true);
        
        proData.altaProducto(producto);
        
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El campo de precio y stock  no pueden estar vacíos");
        }
       
                
        
    }//GEN-LAST:event_jBaltaProductoActionPerformed

    private void jCcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcategoriaActionPerformed
        //cargarComboCategoria();

    }//GEN-LAST:event_jCcategoriaActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed
        
    private void jCcomboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcomboMarcaActionPerformed
        //cargarComboMarca();
    }//GEN-LAST:event_jCcomboMarcaActionPerformed

    private void jCmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmodeloActionPerformed
        //cargarComboModelo();
    }//GEN-LAST:event_jCmodeloActionPerformed

    private void jCnombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCnombreProductoActionPerformed
        //cargarComboNombreProducto();
    }//GEN-LAST:event_jCnombreProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBaltaProducto;
    private javax.swing.JComboBox<String> jCcategoria;
    private javax.swing.JComboBox<String> jCcomboMarca;
    private javax.swing.JComboBox<String> jCmodelo;
    private javax.swing.JComboBox<String> jCnombreProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTdescripcion;
    private javax.swing.JTextField jTprecio;
    private javax.swing.JTextField jTstock;
    // End of variables declaration//GEN-END:variables

    private void cargarComboCategoria ()
    {
        //jCcategoria.removeAllItems();
        List<String> categ = new ArrayList<>();
        categ.add("Electrodomésticos");
        categ.add("Celulares y accesorios");
        categ.add("Tecnología");
        //categ.add("Pequeño Electro");
        
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(categ.toArray(new String[0]));    
        jCcategoria.setModel(comboBoxModel);
        
     
        
        jCcategoria.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarComboNombreProducto();
            }
        });
        
        
        
         
    }
    
        private void cargarComboNombreProducto ()
    {
        
        
        String categoriaSeleccionada = (String) jCcategoria.getSelectedItem();
       
        //jCnombreProducto.removeAllItems();
                
        List<String> nprod = new ArrayList<>();
        
        if (categoriaSeleccionada.equals("Electrodomésticos")){
        
        nprod.add("Heladeras");
        nprod.add("Lavarropas");
        nprod.add("Televisores");
        nprod.add("Cocinas");
        }
        
        else if (categoriaSeleccionada.equals("Tecnología")){
        nprod.add("Notebook");
        nprod.add("Tablets");
        }
        
        else if (categoriaSeleccionada.equals("Celulares y accesorios")){
        nprod.add("Teléfonos");
        }

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(nprod.toArray(new String[0]));    
        jCnombreProducto.setModel(comboBoxModel);
        
        jCnombreProducto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    cargarComboMarca();
                
                   
            }
        });
    }
    
        private void cargarComboMarca ()
    {
        String categoriaSeleccionada = (String) jCcategoria.getSelectedItem();
        String productoSeleccionado = (String) jCnombreProducto.getSelectedItem();
        
        List<String> marca = new ArrayList<>();
        
       if (productoSeleccionado.equals("Heladeras")) {
                   
        marca.add("Whirpool");
        marca.add("Siam");
        }
        else if (productoSeleccionado.equals("Teléfonos")) {
        marca.add("Samsung");
        
        }
        else if (productoSeleccionado.equals("Televisores")) {
        marca.add("LG");
        marca.add("TCL");

        
        }
        
        else if (productoSeleccionado.equals("Tablets")){
        marca.add("Apple");
        }
        
               
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(marca.toArray(new String[0]));    
        jCcomboMarca.setModel(comboBoxModel);
        
        jCcomboMarca.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarComboModelo();
            }
        });
    }
        
     private void cargarComboModelo ()
    {
        String categoriaSeleccionada = (String) jCcategoria.getSelectedItem();
        String productoSeleccionado = (String) jCnombreProducto.getSelectedItem();
        String marcaSeleccionada = (String) jCcomboMarca.getSelectedItem();
        
        List<String> modelo = new ArrayList<>();
        
        if (marcaSeleccionada.equals("Whirpool")) {
        
        modelo.add("WRE85AB");
        modelo.add("WRM57K2");
        modelo.add("WRM53JK");
        }
        else if (marcaSeleccionada.equals("LG")) {
        
        modelo.add("32 pulgadas ");
        modelo.add("43 pulgadas");
        modelo.add("60 pulgadas");
        
        }
        else if (marcaSeleccionada.equals("Samsung")){
        modelo.add("Galaxy A51");
        modelo.add("Galaxy A04");
        modelo.add("Galaxy 24");
        }
        
        else if (marcaSeleccionada.equals("Apple")){
        modelo.add("Ipad Pro 11");
        modelo.add("Ipad 9a Generacion");
        modelo.add("Ipad Air");
        }
        
        
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(modelo.toArray(new String[0]));    
        jCmodelo.setModel(comboBoxModel);
        
        //jCmodelo.addActionListener(jCmodelo);
    }   
}
