/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fravemaxsalesmanager.interfazDeUsuario;

import fravemaxsalesmanager.accesoADatos.ProductoData;
import fravemaxsalesmanager.entidades.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author jfneg
 */
public class ViewModificaInventario extends javax.swing.JInternalFrame {

    ProductoData proData = new ProductoData();

    public ViewModificaInventario() {
      
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        setBorder(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = jPanel = new fravemaxsalesmanager.interfazDeUsuario.BackgroundPanel();
        jLbuscarProducto = new javax.swing.JLabel();
        jTbuscarID = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproductoSeleccionado = new javax.swing.JTable();

        setBorder(null);

        jPanel.setDoubleBuffered(false);
        jPanel.setOpaque(false);

        jLbuscarProducto.setText("Buscar producto por ID: ");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTproductoSeleccionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Id Producto", ""},
                {"Categoría", ""},
                {"Nombre", ""},
                {"Marca", null},
                {"Modelo", null},
                {"Descripción", null},
                {"Precio", null},
                {"Stock", null}
            },
            new String [] {
                "", "Producto Seleccionado"
            }
        ));
        jScrollPane1.setViewportView(jTproductoSeleccionado);
        if (jTproductoSeleccionado.getColumnModel().getColumnCount() > 0) {
            jTproductoSeleccionado.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTbuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jBBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTbuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(122, 122, 122)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        cargarDatosTabla();
    }//GEN-LAST:event_jBBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JLabel jLbuscarProducto;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTbuscarID;
    private javax.swing.JTable jTproductoSeleccionado;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosTabla() {
        try {
            int id = Integer.parseInt(jTbuscarID.getText().replace(" ", ""));

            Producto producto = proData.buscarProductoPorId(id);
            if (producto.getIdProducto() == 0) { 
                jTproductoSeleccionado.setValueAt(null, 0, 1);
                jTproductoSeleccionado.setValueAt(null, 1, 1);
                jTproductoSeleccionado.setValueAt(null, 2, 1);
                jTproductoSeleccionado.setValueAt(null, 3, 1);
                jTproductoSeleccionado.setValueAt(null, 4, 1);
                jTproductoSeleccionado.setValueAt(null, 5, 1);
                jTproductoSeleccionado.setValueAt(null, 6, 1);
                jTproductoSeleccionado.setValueAt(null, 7, 1);
                JOptionPane.showMessageDialog(null, "Error, producto no encontrado.");
            } else {
                jTproductoSeleccionado.setValueAt(producto.getIdProducto(), 0, 1);
                jTproductoSeleccionado.setValueAt(producto.getCategoria(), 1, 1);
                jTproductoSeleccionado.setValueAt(producto.getNombreProducto(), 2, 1);
                jTproductoSeleccionado.setValueAt(producto.getMarca(), 3, 1);
                jTproductoSeleccionado.setValueAt(producto.getModelo(), 4, 1);
                jTproductoSeleccionado.setValueAt(producto.getDescripcion(), 5, 1);
                jTproductoSeleccionado.setValueAt(producto.getPrecioActual(), 6, 1);
                jTproductoSeleccionado.setValueAt(producto.getStock(), 7, 1);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ha ingresado una Id Inválida");
        }
    }
}
