/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fravemaxsalesmanager.interfazDeUsuario;

import fravemaxsalesmanager.accesoADatos.ClienteData;
import fravemaxsalesmanager.accesoADatos.ProductoData;
import fravemaxsalesmanager.accesoADatos.UbicacionData;
import fravemaxsalesmanager.entidades.Cliente;
import fravemaxsalesmanager.entidades.Producto;
import fravemaxsalesmanager.entidades.Ubicacion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jfneg
 */
public class ViewModificaBajaCliente extends javax.swing.JInternalFrame {

    UbicacionData ubiData = new UbicacionData();
    ClienteData cliData = new ClienteData();

    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            if (row == 7 && column == 1){//stock
                return false;
            }
            return true;
        }
    };

    public ViewModificaBajaCliente() {
      
        initComponents();
                
        setBorder(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new fravemaxsalesmanager.interfazDeUsuario.Backinventarios();
        jLbuscarProducto = new javax.swing.JLabel();
        jTbuscarID = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClienteSeleccionado = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 0 || row == 0){return false;}

                return true; // 7 es el índice de la columna "stock"
            }
        };
        jBModificar = new javax.swing.JButton();
        jBBaja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel.setDoubleBuffered(false);
        jPanel.setOpaque(false);

        jLbuscarProducto.setText("Buscar cliente por ID: ");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTClienteSeleccionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Id Cliente", ""},
                {"Nombre", ""},
                {"Apellido", ""},
                {"Cuil", null},
                {"Teléfono", null},
                {"E-mail", null},
                {"Dirección", null},
                {"Código Postal", ""},
                {"Localidad", null},
                {"Provincia", null},
                {"País", null}
            },
            new String [] {
                "", "Cliente Seleccionado"
            }
        ));
        jScrollPane1.setViewportView(jTClienteSeleccionado);
        if (jTClienteSeleccionado.getColumnModel().getColumnCount() > 0) {
            jTClienteSeleccionado.getColumnModel().getColumn(1).setResizable(false);
        }

        jBModificar.setText("Modificar y Guardar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBBaja.setText("Baja");
        jBBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBajaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Modificación y Baja de Clientes");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fravemaxsalesmanager/recursos/cerrar.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTbuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jBBuscar)
                                .addGap(209, 209, 209))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(jBBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTbuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        cargarDatosTabla();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
             
        try {
        // Obtener los valores de la tabla (asegúrate de que los nombres sean correctos)
        int idCliente= (int) jTClienteSeleccionado.getValueAt(0, 1);
        String nombre = (String) jTClienteSeleccionado.getValueAt(1, 1);
        String apellido = (String) jTClienteSeleccionado.getValueAt(2, 1);
        String cuil = (String) jTClienteSeleccionado.getValueAt(3, 1);
        String telefono = (String) jTClienteSeleccionado.getValueAt(4, 1);
        String email = (String) jTClienteSeleccionado.getValueAt(5, 1);
        
        Cliente clienteBusqueda = cliData.obtenerClientePorId(idCliente);
        int idUbicacion = clienteBusqueda.getUbicacion().getIdUbicacion();
        String direccion = (String) jTClienteSeleccionado.getValueAt(6, 1);
        String localidad = (String) jTClienteSeleccionado.getValueAt(7, 1);
        String codigoPostal = (String) jTClienteSeleccionado.getValueAt(8, 1);
        String provincia = (String) jTClienteSeleccionado.getValueAt(9, 1);
        String pais= (String) jTClienteSeleccionado.getValueAt(10, 1);

        // Crear un nuevo objeto Cliente/Ubicacion con los valores modificados
        
        Ubicacion ubicacionModificada = new Ubicacion(idUbicacion, direccion, localidad, codigoPostal, provincia, pais);
        Cliente clienteModificado = new Cliente(idCliente, apellido, nombre, telefono, email, cuil, ubicacionModificada);

        // Actualizar el Cliente/Ubicacion en la base de datos
        ubiData.modificarUbicacion(ubicacionModificada);
        cliData.modificarCliente(clienteModificado);
        JOptionPane.showMessageDialog(null, "Cliente modificado con exito!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al procesar los datos del cliente."+e.getMessage());
    }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBajaActionPerformed
            try {
        // Obtener el ID del producto a dar de baja (supongamos que se ingresa un ID en un campo de texto)
        int idCliente = Integer.parseInt(jTbuscarID.getText().trim());

        // Usar ProductoData para dar de baja el producto en la base de datos
        cliData.eliminarCliente(idCliente);
        limpiarTabla();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al procesar la baja al cliente.");
    }
    }//GEN-LAST:event_jBBajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBaja;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbuscarProducto;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClienteSeleccionado;
    private javax.swing.JTextField jTbuscarID;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosTabla() {
        try {
    
            int id = Integer.parseInt(jTbuscarID.getText().replace(" ", ""));

            Cliente cliente = cliData.obtenerClientePorId(id);
            
            if (cliente.getIdCliente() == 0) {
                limpiarTabla();
                JOptionPane.showMessageDialog(null, "Error, cliente no encontrado.");
            } else {
                jTClienteSeleccionado.setValueAt(cliente.getIdCliente(), 0, 1);
                jTClienteSeleccionado.setValueAt(cliente.getNombre(), 1, 1);
                jTClienteSeleccionado.setValueAt(cliente.getApellido(), 2, 1);
                jTClienteSeleccionado.setValueAt(cliente.getCuil(), 3, 1);
                jTClienteSeleccionado.setValueAt(cliente.getTelef(), 4, 1);
                jTClienteSeleccionado.setValueAt(cliente.getEmail(), 5, 1);
                jTClienteSeleccionado.setValueAt(cliente.getUbicacion().getDireccion(), 6, 1);
                jTClienteSeleccionado.setValueAt(cliente.getUbicacion().getCodigoPostal(), 7, 1);
                jTClienteSeleccionado.setValueAt(cliente.getUbicacion().getLocalidad(), 8, 1);
                jTClienteSeleccionado.setValueAt(cliente.getUbicacion().getProvincia(), 9, 1);
                jTClienteSeleccionado.setValueAt(cliente.getUbicacion().getPais(), 10, 1);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ha ingresado una Id Inválida");
        }
        
    }
   private void limpiarTabla(){
       jTClienteSeleccionado.setValueAt(null, 0, 1);
       jTClienteSeleccionado.setValueAt(null, 1, 1);
       jTClienteSeleccionado.setValueAt(null, 2, 1);
       jTClienteSeleccionado.setValueAt(null, 3, 1);
       jTClienteSeleccionado.setValueAt(null, 4, 1);
       jTClienteSeleccionado.setValueAt(null, 5, 1);
       jTClienteSeleccionado.setValueAt(null, 6, 1);
       jTClienteSeleccionado.setValueAt(null, 7, 1);
   }

}
    

